import { z } from 'zod';

export const createPropertyValidator = z.object({
  title: z.string().min(10, 'Title should be between 10 and 100 characters').max(100).trim(),
  description: z.any().refine((val) => val !== undefined && val !== null, 'Description is required'),
  propertyType: z.enum(['flat', 'terraced', 'semi-detached', 'detached', 'maisonette', 'bungalow']),
  bedrooms: z.number().min(0, 'Bedrooms cannot be negative'),
  bathrooms: z.number().min(0, 'Bathrooms cannot be negative'),
  sqft: z.number().positive('Floor area must be a positive number'),
  address: z.string().min(1, 'Full address is required').trim(),
  location: z.string().min(1, 'Location is required').trim(),
  postcode: z.string().min(1, 'Postcode is required').trim().regex(/^[A-Z]{1,2}[0-9R][0-9A-Z]?$/i, 'Please enter a valid UK postcode outcode (e.g., M5, LS1, SW1A).'),
  tenure: z.enum(['freehold', 'leasehold', 'share-of-freehold']),
  heroImage: z.string().min(1, 'Hero image is required').trim(),
  gallery: z.array(z.any()).max(8, 'Gallery cannot have more than 8 photos').optional().default([]),
  investmentMetrics: z.object({
    askingPrice: z.number().positive('Asking price must be positive'),
    monthlyRent: z.number().positive('Monthly rent must be positive'),
    leaseYearsRemaining: z.number().min(0, 'Lease years remaining must be positive').int().optional()
  }),
  serviceCharge: z.number().min(0).optional().default(0),
  groundRent: z.number().min(0).optional().default(0),
  councilTaxBand: z.enum(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']).optional(),
  tenented: z.boolean().optional().default(true),
  tenancyStatus: z.string().optional(),
  tenantMoveInDate: z.string().optional().transform((val) => val ? new Date(val) : undefined),
  contractType: z.enum(['ast', 'non-ast', 'company-let', 'license']).optional(),
  rentCollectionStatus: z.enum(['agent-managed', 'direct-to-landlord', 'guaranteed']).optional(),
  arrearsStatus: z.enum(['no-arrears', 'historical-resolved', 'active-arrears']).optional().default('no-arrears'),
  tenancyNotes: z.string().optional(),
  epc: z.string().optional(),
  priceType: z.enum(['guide-price', 'fixed-price', 'offers-over']).optional().nullable(),
  tenancyStartDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  tenancyType: z.enum(['ast', 'non-ast', 'company-let', 'license']).optional().nullable(),
  fixedTermEndDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  rentPaymentStatus: z.enum(['up-to-date', 'partially-paid', 'overdue']).optional().nullable(),
  depositProtected: z.boolean().optional().nullable(),
  noticeServed: z.boolean().optional().nullable(),
  tenantWantsToStay: z.enum(['yes', 'no', 'unknown']).optional().nullable(),
  viewingArrangements: z.enum(['vacant-access', 'accompanied', 'tenant-notify-24h', 'tenant-notify-48h']).optional().nullable(),
  rentReviewDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  compliance: z.any().optional().nullable(),
  mediaFiles: z.array(z.any()).optional().default([]),
  floorplans: z.array(z.any()).max(3, 'Floor plans cannot have more than 3 images').optional().default([]),
  propertyPacks: z.array(z.any()).optional().default([]),
  complianceDocuments: z.array(z.any()).optional().default([]),
  status: z.enum(['draft', 'pending-review', 'published', 'under-offer', 'sold', 'archived']).optional().default('draft'),
  displayOnHomepage: z.boolean().optional().default(false),
  isFeatured: z.boolean().optional().default(false),
  isHighYield: z.boolean().optional().default(false),
  latitude: z.number().optional(),
  longitude: z.number().optional()
});

export const updatePropertyValidator = z.object({
  title: z.string().min(10).max(100).trim().optional(),
  description: z.any().optional(),
  propertyType: z.enum(['flat', 'terraced', 'semi-detached', 'detached', 'maisonette', 'bungalow']).optional(),
  bedrooms: z.number().min(0).optional(),
  bathrooms: z.number().min(0).optional(),
  sqft: z.number().positive().optional(),
  address: z.string().min(1).trim().optional(),
  location: z.string().trim().optional(),
  postcode: z.string().trim().regex(/^[A-Z]{1,2}[0-9R][0-9A-Z]?$/i, 'Please enter a valid UK postcode outcode (e.g., M5, LS1, SW1A).').optional(),
  tenure: z.enum(['freehold', 'leasehold', 'share-of-freehold']).optional(),
  heroImage: z.string().trim().optional(),
  gallery: z.array(z.any()).max(8, 'Gallery cannot have more than 8 photos').optional(),
  investmentMetrics: z.object({
    askingPrice: z.number().positive().optional(),
    monthlyRent: z.number().positive().optional(),
    leaseYearsRemaining: z.number().min(0).int().optional()
  }).partial().optional(),
  serviceCharge: z.number().min(0).optional(),
  groundRent: z.number().min(0).optional(),
  councilTaxBand: z.enum(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']).optional(),
  tenented: z.boolean().optional(),
  tenancyStatus: z.string().optional(),
  tenantMoveInDate: z.string().optional().transform((val) => val ? new Date(val) : undefined),
  contractType: z.enum(['ast', 'non-ast', 'company-let', 'license']).optional(),
  rentCollectionStatus: z.enum(['agent-managed', 'direct-to-landlord', 'guaranteed']).optional(),
  arrearsStatus: z.enum(['no-arrears', 'historical-resolved', 'active-arrears']).optional(),
  tenancyNotes: z.string().optional(),
  epc: z.string().optional(),
  priceType: z.enum(['guide-price', 'fixed-price', 'offers-over']).optional().nullable(),
  tenancyStartDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  tenancyType: z.enum(['ast', 'non-ast', 'company-let', 'license']).optional().nullable(),
  fixedTermEndDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  rentPaymentStatus: z.enum(['up-to-date', 'partially-paid', 'overdue']).optional().nullable(),
  depositProtected: z.boolean().optional().nullable(),
  noticeServed: z.boolean().optional().nullable(),
  tenantWantsToStay: z.enum(['yes', 'no', 'unknown']).optional().nullable(),
  viewingArrangements: z.enum(['vacant-access', 'accompanied', 'tenant-notify-24h', 'tenant-notify-48h']).optional().nullable(),
  rentReviewDate: z.string().optional().nullable().transform((val) => val ? new Date(val) : undefined),
  compliance: z.any().optional().nullable(),
  mediaFiles: z.array(z.any()).optional(),
  floorplans: z.array(z.any()).max(3, 'Floor plans cannot have more than 3 images').optional(),
  propertyPacks: z.array(z.any()).optional(),
  complianceDocuments: z.array(z.any()).optional(),
  status: z.enum(['draft', 'pending-review', 'published', 'under-offer', 'sold', 'archived']).optional(),
  displayOnHomepage: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
  isHighYield: z.boolean().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional()
});
